### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by codinfox** [adueck/good-clean-read#3]
1. There is a layout named "page.html", but it is used nowhere. Should it be deleted?
2. [Here](https://github.com/adueck/good-clean-read/blob/master/_layouts/default.html#L16) is a resource link to `{{ site.ull }}`, but inside `_config.yml` there is no such field. Could you please provide an example inside `_config.yml`?

**Comment by adueck** [comment]
1. Hmm... I think you're right but let me just double check on that.
2. That was a mistake, it's supposed to read `{{ site.url }}` and I just fixed that. 

Thanks for the help!

**Comment by adueck** [comment]
In response to your first question:

You're right that `page.html` is not used anywhere but some people might like to use it to make a second page or another linked article. You could do that by putting `layout: page` in the yaml front matter of another .md file and it would do it nicely. So I will keep `page.html` in the repo.
